In [1]:
from model.model import get_model
import os
from dotenv import load_dotenv
from outlines import Generator, from_transformers  
from schema.ticket import Ticket 
from prompt.summarizer import summary_prompt
from schema.table import Table
import json
from evalution.metric import TicketEvaluator
load_dotenv()

True

In [2]:
location = os.getenv('DATA_FILE_NAME')
table_1 = Table(location)

In [3]:
name = os.getenv('MODEL_NAME')
hf_model,hf_tokenizer = get_model(name)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

model downloaded

In [4]:
hf_model.eval()

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)

In [5]:
model = from_transformers(hf_model,hf_tokenizer)

In [6]:
generator = Generator(model,Ticket)

In [7]:
evaluator = TicketEvaluator(generator=generator)

In [8]:
#metric = evaluator.evalute_ticket(table_1.return_ticket(1),max_new_tokens=150,use_cache= True)

In [9]:
df = evaluator.evalutaion_dataframe(max_new_tokens=150,use_cache= True)

ticket_id                                                    1
message      My laptop screen is broken and I need urgent h...
category                                             technical
sentiment                                             negative
urgency                                                   high
Name: 0, dtype: object

W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415] WON'T CONVERT _apply_token_bitmask_inplace_kernel d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\outlines_core\kernels\torch.py line 43
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415] due to:
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415] Traceback (most recent call last):
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 2319, in __call__
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     result = self._inner_convert(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         frame, cache_entry, hooks, frame_state, skip=skip + 1
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 777, in __call__
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     result = _compile(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         frame.f_code,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<18 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         convert_frame_box=self._box,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 2102, in _compile
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     guarded_code, tracer_output = compile_inner(code, one_graph, hooks)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]                                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_utils_internal.py", line 96, in wrapper_function
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return function(*args, **kwargs)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1687, in compile_inner
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     result = _compile_inner(code, one_graph, hooks)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1747, in _compile_inner
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     dynamo_output = compile_frame(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         code,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<11 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         package=package,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1584, in compile_frame
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     bytecode, tracer_output = transform_code_object(code, transform)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1821, in transform_code_object
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     tracer_output = transformations(instructions, code_options)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1555, in transform
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     tracer_output = trace_frame(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         code,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<14 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         package=package,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 368, in _fn
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return fn(*args, **kwargs)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 954, in trace_frame
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     run_tracer()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 935, in run_tracer
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     tracer.run()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 1950, in run
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     while self.step():
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]           ~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 1603, in step
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self.dispatch_table[inst.opcode](self, inst)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 5619, in RETURN_CONST
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self._return(inst)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~~~^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 5589, in _return
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     all_stack_locals_metadata = self.output.compile_subgraph(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         self,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<4 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         stack_pops=1 if inst.opname == "RETURN_VALUE" else 0,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 2234, in compile_subgraph
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     instructions, subgraph_pycode = self.compile_and_call_fx_graph(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         tx, pass2.graph_output_vars(), root
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 2880, in compile_and_call_fx_graph
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     compiled_fn = self.call_user_compiler(gm, self.example_inputs())
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 3057, in call_user_compiler
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return self._call_user_compiler(gm, example_inputs)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 3119, in _call_user_compiler
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     compiled_fn = compiler_fn(gm, example_inputs)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 159, in __call__
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     compiled_gm = compiler_fn(gm, example_inputs)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\__init__.py", line 2489, in __call__
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return compile_fx(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         model_,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<2 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         compile_region_name=self.name,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 2782, in compile_fx
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return _maybe_wrap_and_compile_fx_main(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         model_,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<4 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         compile_region_name=compile_region_name,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 2863, in _maybe_wrap_and_compile_fx_main
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return _compile_fx_main(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         model_,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<4 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         compile_region_name=compile_region_name,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 3076, in _compile_fx_main
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1079, in _compile_fx_inner
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     raise InductorError(e, currentframe()).with_traceback(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         e.__traceback__
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ) from None
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1059, in _compile_fx_inner
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     mb_compiled_graph = fx_codegen_and_compile(
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         gm,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ...<3 lines>...
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]         **graph_kwargs,
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     )
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1847, in fx_codegen_and_compile
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1608, in codegen_and_compile
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     compiled_module = graph.compile_to_module()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2669, in compile_to_module
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     return self._compile_to_module()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]            ~~~~~~~~~~~~~~~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2675, in _compile_to_module
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]                                                              ~~~~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2611, in codegen
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self.scheduler.codegen()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~~~~~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 9206, in codegen
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self._codegen_partitions()
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~~~~~~~~~~~~~~~^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 9354, in _codegen_partitions
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self._codegen(partition)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~~~~^^^^^^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\scheduler.py", line 9508, in _codegen
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self.get_backend(device).codegen_node(node)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\codegen\cpp.py", line 5550, in codegen_node
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     cpp_kernel_proxy = self.kernel_proxy_cls(kernel_group)
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]   File "d:\Programing\Depi\ticket_summary\ticket_summary\.venv\Lib\site-packages\torch\_inductor\codegen\cpp.py", line 4182, in __init__
W0910 16:51:38.764000 33248 Lib\site-packages\torch\_dynamo\convert_frame.py:2415]     self.picked_vec_isa: cpu_vec_isa.VecISA = cpu_vec_isa.pick_vec_isa()

ticket_id                                             2
message      I forgot my password and need to reset it.
category                                        account
sentiment                                       neutral
urgency                                          medium
Name: 1, dtype: object
ticket_id                                    3
message      My package arrived two days late.
category                              delivery
sentiment                             negative
urgency                                 medium
Name: 2, dtype: object
ticket_id                                          4
message      I was charged twice for the same order.
category                                     billing
sentiment                                   negative
urgency                                         high
Name: 3, dtype: object
ticket_id                                    5
message      I want to cancel my subscription.
category                          subscription
sentiment                              neutral
urgency                                 medium
Name: 4, dtype: object
ticket_id                                                 6
message      Your support team was very helpful, thank you!
category                                            account
sentiment                                          positive
urgency                                                 low
Name: 5, dtype: object
ticket_id                                                    7
message      The payment failed but money was deducted from...
category                                               billing
sentiment                                             negative
urgency                                                   high
Name: 6, dtype: object
ticket_id                                                    8
message      I received my order early and everything looks...
category                                              delivery
sentiment                                             positive
urgency                                                    low
Name: 7, dtype: object
ticket_id                                               9
message      The mobile app freezes when I upload a file.
category                                        technical
sentiment                                        negative
urgency                                              high
Name: 8, dtype: object
ticket_id                                         10
message      How can I upgrade my subscription plan?
category                                subscription
sentiment                                    neutral
urgency                                          low
Name: 9, dtype: object

In [18]:
df

,ticket_id,message,category,sentiment,urgency,success,pred_category,pred_sentiment,pred_urgency,pred_summary,category_accuracy,sentiment_accuracy,urgency_accuracy
0,1,My laptop screen is broken and I need urgent h...,technical,negative,high,True,technical,negative,high,Customer needs urgent technical support due to...,True,True,True
1,2,I forgot my password and need to reset it.,account,neutral,medium,True,account,neutral,low,Customer wants assistance with resetting their...,True,True,False
2,3,My package arrived two days late.,delivery,negative,medium,True,delivery,negative,high,Package delay after expected delivery time.,True,True,False
3,4,I was charged twice for the same order.,billing,negative,high,True,billing,negative,high,Customer had to pay twice for the same order.,True,True,True
4,5,I want to cancel my subscription.,subscription,neutral,medium,True,subscription,negative,low,Customer wants to end their current subscripti...,True,False,False
5,6,"Your support team was very helpful, thank you!",account,positive,low,True,subscription,positive,low,Customer appreciated the support from their su...,False,True,True
6,7,The payment failed but money was deducted from...,billing,negative,high,True,technical,neutral,high,Payment failed and funds were debited from you...,False,False,True
7,8,I received my order early and everything looks...,delivery,positive,low,True,delivery,positive,low,Order delivered on time with satisfactory qual...,True,True,True
8,9,The mobile app freezes when I upload a file.,technical,negative,high,True,technical,negative,high,File upload causing freeze on mobile app,True,True,True
9,10,How can I upgrade my subscription plan?,subscription,neutral,low,True,technical,neutral,high,Customer needs help upgrading their subscripti...,False,True,False

In [15]:
metric=evaluator.accuracy_metric(df)

clean_metric = {k:float(v) for k,v in metric.items()}

In [16]:
clean_metric

{'category_accuracy': 70.0,
 'sentiment_accuracy': 80.0,
 'urgency_accuracy': 60.0}

In [17]:
#result = generator(summary_prompt(table_1.return_ticket(2)), max_new_tokens=150,use_cache= True)
#print(result)

In [13]:
output = Ticket.model_validate_json(result)
output = output.model_dump_json()

NameError: name 'result' is not defined

In [ ]:
output = json.loads(output)

In [ ]:
output['category']

'delivery'

In [ ]:
table_1.return_row(1)

,ticket_id,message,category,sentiment,urgency
8,9,The mobile app freezes when I upload a file.,technical,negative,high